// Code generated by protocol/codegen -- DO NOT EDIT.
// Source of truth: protocol/schema/**. Regenerate with `make protocol` at the repo root.
// CI fails if this file is stale.

package dev.claudewear.protocol

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

public const val PROTOCOL_VERSION: Long = 1

/** Events that belong to the registry rather than to one chat carry this sessionId. */
public const val REGISTRY_SESSION_ID: String = "@registry"

/** Mirrors the Agent SDK result message subtypes. */
@Serializable
public enum class DoneSubtype {
    @SerialName("success") SUCCESS,
    @SerialName("error_max_turns") ERROR_MAX_TURNS,
    @SerialName("error_during_execution") ERROR_DURING_EXECUTION,
}

@Serializable
public enum class ErrorCode {
    @SerialName("unauthorized") UNAUTHORIZED,
    @SerialName("protocolVersion") PROTOCOL_VERSION,
    @SerialName("malformed") MALFORMED,
    @SerialName("unknownSession") UNKNOWN_SESSION,
    @SerialName("unknownRequest") UNKNOWN_REQUEST,
    @SerialName("alreadyResolved") ALREADY_RESOLVED,
    @SerialName("maxSessions") MAX_SESSIONS,
    @SerialName("invalidCwd") INVALID_CWD,
    @SerialName("runnerFailed") RUNNER_FAILED,
    @SerialName("internal") INTERNAL,
}

/** What the wearer tapped on a permission card. */
@Serializable
public enum class PermissionDecision {
    @SerialName("allow") ALLOW,
    @SerialName("allowAlways") ALLOW_ALWAYS,
    @SerialName("deny") DENY,
}

/** Agent SDK permission mode. The notification-volume knob: anything auto-approved never reaches canUseTool and so never buzzes the wrist. */
@Serializable
public enum class PermissionMode {
    @SerialName("default") DEFAULT,
    @SerialName("acceptEdits") ACCEPT_EDITS,
    @SerialName("plan") PLAN,
    @SerialName("bypassPermissions") BYPASS_PERMISSIONS,
}

/** How a pending request stopped being pending. */
@Serializable
public enum class Resolution {
    @SerialName("answered") ANSWERED,
    @SerialName("allowed") ALLOWED,
    @SerialName("denied") DENIED,
    @SerialName("cancelled") CANCELLED,
    @SerialName("interrupted") INTERRUPTED,
}

/** Lifecycle of one chat as the watch sees it. */
@Serializable
public enum class SessionState {
    @SerialName("starting") STARTING,
    @SerialName("working") WORKING,
    @SerialName("awaiting") AWAITING,
    @SerialName("idle") IDLE,
    @SerialName("closed") CLOSED,
    @SerialName("error") ERROR,
}

/** Why the session's turn state changed. */
@Serializable
public enum class TurnReason {
    @SerialName("started") STARTED,
    @SerialName("ask") ASK,
    @SerialName("permission") PERMISSION,
    @SerialName("result") RESULT,
    @SerialName("interrupted") INTERRUPTED,
    @SerialName("failed") FAILED,
}

/** One chip on a question card. */
@Serializable
public data class AskOption(
    public val label: String,
    public val description: String?,
)

/** One AskUserQuestion question. header is <=12 chars and is made for exactly this screen size. */
@Serializable
public data class AskQuestion(
    public val question: String,
    public val header: String,
    public val options: List<AskOption>,
    public val multiSelect: Boolean,
)

@Serializable
public data class PermissionRule(
    public val toolName: String,
    public val ruleContent: String?,
)

/** An 'always allow' rule the SDK offered. Echoed back verbatim when the wearer taps Always, filtered to destination == localSettings. */
@Serializable
public data class PermissionSuggestion(
    public val type: String,
    public val behavior: String?,
    public val destination: String?,
    public val rules: List<PermissionRule>,
)

/** One row of the watch's session list. */
@Serializable
public data class SessionSummary(
    public val sessionId: String,
    /** User-set label; defaults to the cwd basename. */
    public val name: String,
    public val cwd: String,
    public val state: SessionState,
    public val mode: PermissionMode,
    /** Highest seq emitted for this session so far. */
    public val seq: Long,
    public val pendingRequestIds: List<String>,
    public val createdAt: Long,
    public val lastActivityAt: Long,
)

/** Anything the watch may send. */
@Serializable
public sealed interface ClientMessage

/** Anything the bridge may send. */
@Serializable
public sealed interface ServerEvent {
    public val sessionId: String

    /** Per-session monotonic sequence number, so the watch can spot a gap and resync. */
    public val seq: Long
}

/** Answer an AskUserQuestion. Set answers to pick options (values are labels, or dictated free text). Set response instead to dismiss the questions and just talk to Claude. Exactly one of the two is non-null. */
@Serializable
@SerialName("answer")
public data class AnswerMessage(
    public val sessionId: String,
    public val requestId: String,
    /** question text -> selected label. multiSelect answers are joined with ', '. */
    public val answers: Map<String, String>?,
    public val response: String?,
) : ClientMessage

/** First frame after the WebSocket upgrade. The bearer token travelled on the upgrade request, not here. */
@Serializable
@SerialName("hello")
public data class HelloMessage(
    public val protocolVersion: Long,
    public val deviceId: String,
    public val deviceName: String,
    public val clientVersion: String,
) : ClientMessage

/** Stop a runaway agent from the wrist. */
@Serializable
@SerialName("interrupt")
public data class InterruptMessage(
    public val sessionId: String,
) : ClientMessage

/** Start a chat in a directory that already exists. The bridge never clones or provisions anything. */
@Serializable
@SerialName("newSession")
public data class NewSessionMessage(
    public val cwd: String,
    /** Defaults to the cwd basename. */
    public val name: String?,
) : ClientMessage

/** Answer a permission card. allowAlways additionally persists the localSettings suggestions the bridge sent with the request. */
@Serializable
@SerialName("permission")
public data class PermissionDecisionMessage(
    public val sessionId: String,
    public val requestId: String,
    public val decision: PermissionDecision,
    /** Deny reason. Claude sees this, so it adapts instead of retrying blindly. */
    public val message: String?,
) : ClientMessage

/** Push a follow-up user message into a live session. */
@Serializable
@SerialName("prompt")
public data class PromptMessage(
    public val sessionId: String,
    public val text: String,
) : ClientMessage

/** Relabel a chat. Every notification card leads with this name, which is what makes two waiting sessions answerable at a glance. */
@Serializable
@SerialName("renameSession")
public data class RenameSessionMessage(
    public val sessionId: String,
    public val name: String,
) : ClientMessage

/** Change a live session's permission mode. Raising it means fewer wrist buzzes and less oversight. */
@Serializable
@SerialName("setMode")
public data class SetModeMessage(
    public val sessionId: String,
    public val mode: PermissionMode,
) : ClientMessage

/** Ask for a full resync. The bridge answers with a sessions snapshot plus a replay of every outstanding request across all sessions. */
@Serializable
@SerialName("subscribe")
public data class SubscribeMessage(
    /** sessionId -> highest seq the client already has. null means the client has nothing. */
    public val sinceSeq: Map<String, Long>?,
) : ClientMessage

/** canUseTool fired for AskUserQuestion. The agent is blocked until an answer or interrupt comes back. */
@Serializable
@SerialName("ask")
public data class AskEvent(
    override val sessionId: String,
    override val seq: Long,
    public val requestId: String,
    /** 1-4 questions, 2-4 options each. */
    public val questions: List<AskQuestion>,
) : ServerEvent

/** A result message arrived: the agent finished its turn and it is yours. */
@Serializable
@SerialName("done")
public data class DoneEvent(
    override val sessionId: String,
    override val seq: Long,
    public val subtype: DoneSubtype,
    public val isError: Boolean,
    public val durationMs: Long,
    public val numTurns: Long,
    public val result: String?,
) : ServerEvent

/** Something the client asked for did not happen. Connection-scoped errors use the reserved '@registry' sessionId. */
@Serializable
@SerialName("error")
public data class ErrorEvent(
    override val sessionId: String,
    override val seq: Long,
    public val code: ErrorCode,
    public val message: String,
    public val requestId: String?,
) : ServerEvent

/** canUseTool fired for a tool that is not AskUserQuestion. The agent is blocked until a decision or interrupt comes back. */
@Serializable
@SerialName("permission")
public data class PermissionEvent(
    override val sessionId: String,
    override val seq: Long,
    public val requestId: String,
    public val tool: String,
    /** The tool input verbatim. */
    public val input: JsonObject,
    /** The actual command or path, never a summary. Approving what you cannot see is the failure mode this product designs against. */
    public val display: String,
    public val suggestions: List<PermissionSuggestion>,
) : ServerEvent

/** A pending request stopped being pending - possibly answered from the CLI, the phone, or another watch. The watch cancels that notification. */
@Serializable
@SerialName("resolved")
public data class ResolvedEvent(
    override val sessionId: String,
    override val seq: Long,
    public val requestId: String,
    public val resolution: Resolution,
    /** deviceId that answered, when a device did. */
    public val by: String?,
) : ServerEvent

/** Snapshot of every chat. Registry-scoped, so sessionId is the reserved id '@registry' and seq counts on the registry's own stream. */
@Serializable
@SerialName("sessions")
public data class SessionsEvent(
    override val sessionId: String,
    override val seq: Long,
    public val sessions: List<SessionSummary>,
    public val maxSessions: Long,
    /** Directories a chat may open, so the watch offers a pick list rather than asking you to type a path on a 1.5" screen. Empty means the bridge is configured permissively and any existing directory will do. */
    public val projectRoots: List<String>,
) : ServerEvent

/** Assistant text, summarised rather than streamed. A watch does not need token-by-token deltas and not sending them is a meaningful battery saving. */
@Serializable
@SerialName("text")
public data class TextEvent(
    override val sessionId: String,
    override val seq: Long,
    public val text: String,
) : ServerEvent

/** The alerting event: this session's turn state changed. state == awaiting or idle is what buzzes the wrist; NotificationTransport consumes exactly this. */
@Serializable
@SerialName("turn")
public data class TurnEvent(
    override val sessionId: String,
    override val seq: Long,
    public val state: SessionState,
    public val reason: TurnReason,
    /** The request that is blocking, when reason is ask or permission. Carried into the notification's RemoteInput so a dictated reply from the shade resolves this exact request. */
    public val requestId: String?,
    /** Denormalised so a notification can be built from the turn event alone. */
    public val sessionName: String,
    /** One line, already shortened for a 1.5" screen. */
    public val summary: String,
) : ServerEvent
