// Code generated by protocol/codegen -- DO NOT EDIT.
// Source of truth: protocol/schema/**. Regenerate with `npm run codegen` in bridge/,
// or `make protocol` at the repo root. CI fails if this file is stale.

export const PROTOCOL_VERSION = 1;

/** Events that belong to the registry rather than to one chat carry this sessionId. */
export const REGISTRY_SESSION_ID = "@registry";

export type JsonSchema = Readonly<Record<string, unknown>>;

/** The shared $defs, so the runtime validator can resolve $ref without reading the repo. */
export const COMMON_SCHEMA: JsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "common.schema.json",
  "title": "Common",
  "description": "Shared definitions referenced by the client and server message schemas.",
  "$defs": {
    "SessionState": {
      "title": "SessionState",
      "description": "Lifecycle of one chat as the watch sees it.",
      "type": "string",
      "enum": [
        "starting",
        "working",
        "awaiting",
        "idle",
        "closed",
        "error"
      ]
    },
    "PermissionMode": {
      "title": "PermissionMode",
      "description": "Agent SDK permission mode. The notification-volume knob: anything auto-approved never reaches canUseTool and so never buzzes the wrist.",
      "type": "string",
      "enum": [
        "default",
        "acceptEdits",
        "plan",
        "bypassPermissions"
      ]
    },
    "TurnReason": {
      "title": "TurnReason",
      "description": "Why the session's turn state changed.",
      "type": "string",
      "enum": [
        "started",
        "ask",
        "permission",
        "result",
        "interrupted",
        "failed"
      ]
    },
    "PermissionDecision": {
      "title": "PermissionDecision",
      "description": "What the wearer tapped on a permission card.",
      "type": "string",
      "enum": [
        "allow",
        "allowAlways",
        "deny"
      ]
    },
    "Resolution": {
      "title": "Resolution",
      "description": "How a pending request stopped being pending.",
      "type": "string",
      "enum": [
        "answered",
        "allowed",
        "denied",
        "cancelled",
        "interrupted"
      ]
    },
    "ErrorCode": {
      "title": "ErrorCode",
      "type": "string",
      "enum": [
        "unauthorized",
        "protocolVersion",
        "malformed",
        "unknownSession",
        "unknownRequest",
        "alreadyResolved",
        "maxSessions",
        "invalidCwd",
        "runnerFailed",
        "internal"
      ]
    },
    "DoneSubtype": {
      "title": "DoneSubtype",
      "description": "Mirrors the Agent SDK result message subtypes.",
      "type": "string",
      "enum": [
        "success",
        "error_max_turns",
        "error_during_execution"
      ]
    },
    "AskOption": {
      "title": "AskOption",
      "description": "One chip on a question card.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "label",
        "description"
      ],
      "properties": {
        "label": {
          "type": "string"
        },
        "description": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "AskQuestion": {
      "title": "AskQuestion",
      "description": "One AskUserQuestion question. header is <=12 chars and is made for exactly this screen size.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "question",
        "header",
        "options",
        "multiSelect"
      ],
      "properties": {
        "question": {
          "type": "string"
        },
        "header": {
          "type": "string"
        },
        "options": {
          "type": "array",
          "items": {
            "$ref": "common.schema.json#/$defs/AskOption"
          }
        },
        "multiSelect": {
          "type": "boolean"
        }
      }
    },
    "PermissionRule": {
      "title": "PermissionRule",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "toolName",
        "ruleContent"
      ],
      "properties": {
        "toolName": {
          "type": "string"
        },
        "ruleContent": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "PermissionSuggestion": {
      "title": "PermissionSuggestion",
      "description": "An 'always allow' rule the SDK offered. Echoed back verbatim when the wearer taps Always, filtered to destination == localSettings.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "behavior",
        "destination",
        "rules"
      ],
      "properties": {
        "type": {
          "type": "string"
        },
        "behavior": {
          "type": [
            "string",
            "null"
          ]
        },
        "destination": {
          "type": [
            "string",
            "null"
          ]
        },
        "rules": {
          "type": "array",
          "items": {
            "$ref": "common.schema.json#/$defs/PermissionRule"
          }
        }
      }
    },
    "SessionSummary": {
      "title": "SessionSummary",
      "description": "One row of the watch's session list.",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "sessionId",
        "name",
        "cwd",
        "state",
        "mode",
        "seq",
        "pendingRequestIds",
        "createdAt",
        "lastActivityAt"
      ],
      "properties": {
        "sessionId": {
          "type": "string"
        },
        "name": {
          "type": "string",
          "description": "User-set label; defaults to the cwd basename."
        },
        "cwd": {
          "type": "string"
        },
        "state": {
          "$ref": "common.schema.json#/$defs/SessionState"
        },
        "mode": {
          "$ref": "common.schema.json#/$defs/PermissionMode"
        },
        "seq": {
          "type": "integer",
          "description": "Highest seq emitted for this session so far."
        },
        "pendingRequestIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "createdAt": {
          "type": "integer"
        },
        "lastActivityAt": {
          "type": "integer"
        }
      }
    }
  }
};

/** Mirrors the Agent SDK result message subtypes. */
export type DoneSubtype = "success" | "error_max_turns" | "error_during_execution";
export const DONE_SUBTYPES: readonly DoneSubtype[] = ["success", "error_max_turns", "error_during_execution"];

export type ErrorCode = "unauthorized" | "protocolVersion" | "malformed" | "unknownSession" | "unknownRequest" | "alreadyResolved" | "maxSessions" | "invalidCwd" | "runnerFailed" | "internal";
export const ERROR_CODES: readonly ErrorCode[] = ["unauthorized", "protocolVersion", "malformed", "unknownSession", "unknownRequest", "alreadyResolved", "maxSessions", "invalidCwd", "runnerFailed", "internal"];

/** What the wearer tapped on a permission card. */
export type PermissionDecision = "allow" | "allowAlways" | "deny";
export const PERMISSION_DECISIONS: readonly PermissionDecision[] = ["allow", "allowAlways", "deny"];

/** Agent SDK permission mode. The notification-volume knob: anything auto-approved never reaches canUseTool and so never buzzes the wrist. */
export type PermissionMode = "default" | "acceptEdits" | "plan" | "bypassPermissions";
export const PERMISSION_MODES: readonly PermissionMode[] = ["default", "acceptEdits", "plan", "bypassPermissions"];

/** How a pending request stopped being pending. */
export type Resolution = "answered" | "allowed" | "denied" | "cancelled" | "interrupted";
export const RESOLUTIONS: readonly Resolution[] = ["answered", "allowed", "denied", "cancelled", "interrupted"];

/** Lifecycle of one chat as the watch sees it. */
export type SessionState = "starting" | "working" | "awaiting" | "idle" | "closed" | "error";
export const SESSION_STATES: readonly SessionState[] = ["starting", "working", "awaiting", "idle", "closed", "error"];

/** Why the session's turn state changed. */
export type TurnReason = "started" | "ask" | "permission" | "result" | "interrupted" | "failed";
export const TURN_REASONS: readonly TurnReason[] = ["started", "ask", "permission", "result", "interrupted", "failed"];

/** One chip on a question card. */
export interface AskOption {
  label: string;
  description: string | null;
}

/** One AskUserQuestion question. header is <=12 chars and is made for exactly this screen size. */
export interface AskQuestion {
  question: string;
  header: string;
  options: AskOption[];
  multiSelect: boolean;
}

export interface PermissionRule {
  toolName: string;
  ruleContent: string | null;
}

/** An 'always allow' rule the SDK offered. Echoed back verbatim when the wearer taps Always, filtered to destination == localSettings. */
export interface PermissionSuggestion {
  type: string;
  behavior: string | null;
  destination: string | null;
  rules: PermissionRule[];
}

/** One row of the watch's session list. */
export interface SessionSummary {
  sessionId: string;
  /** User-set label; defaults to the cwd basename. */
  name: string;
  cwd: string;
  state: SessionState;
  mode: PermissionMode;
  /** Highest seq emitted for this session so far. */
  seq: number;
  pendingRequestIds: string[];
  createdAt: number;
  lastActivityAt: number;
}

/** Answer an AskUserQuestion. Set answers to pick options (values are labels, or dictated free text). Set response instead to dismiss the questions and just talk to Claude. Exactly one of the two is non-null. */
export interface AnswerMessage {
  type: "answer";
  sessionId: string;
  requestId: string;
  /** question text -> selected label. multiSelect answers are joined with ', '. */
  answers: Record<string, string> | null;
  response: string | null;
}

/** First frame after the WebSocket upgrade. The bearer token travelled on the upgrade request, not here. */
export interface HelloMessage {
  type: "hello";
  protocolVersion: number;
  deviceId: string;
  deviceName: string;
  clientVersion: string;
}

/** Stop a runaway agent from the wrist. */
export interface InterruptMessage {
  type: "interrupt";
  sessionId: string;
}

/** Start a chat in a directory that already exists. The bridge never clones or provisions anything. */
export interface NewSessionMessage {
  type: "newSession";
  cwd: string;
  /** Defaults to the cwd basename. */
  name: string | null;
}

/** Answer a permission card. allowAlways additionally persists the localSettings suggestions the bridge sent with the request. */
export interface PermissionDecisionMessage {
  type: "permission";
  sessionId: string;
  requestId: string;
  decision: PermissionDecision;
  /** Deny reason. Claude sees this, so it adapts instead of retrying blindly. */
  message: string | null;
}

/** Push a follow-up user message into a live session. */
export interface PromptMessage {
  type: "prompt";
  sessionId: string;
  text: string;
}

/** Relabel a chat. Every notification card leads with this name, which is what makes two waiting sessions answerable at a glance. */
export interface RenameSessionMessage {
  type: "renameSession";
  sessionId: string;
  name: string;
}

/** Change a live session's permission mode. Raising it means fewer wrist buzzes and less oversight. */
export interface SetModeMessage {
  type: "setMode";
  sessionId: string;
  mode: PermissionMode;
}

/** Ask for a full resync. The bridge answers with a sessions snapshot plus a replay of every outstanding request across all sessions. */
export interface SubscribeMessage {
  type: "subscribe";
  /** sessionId -> highest seq the client already has. null means the client has nothing. */
  sinceSeq: Record<string, number> | null;
}

/** canUseTool fired for AskUserQuestion. The agent is blocked until an answer or interrupt comes back. */
export interface AskEvent {
  type: "ask";
  sessionId: string;
  seq: number;
  requestId: string;
  /** 1-4 questions, 2-4 options each. */
  questions: AskQuestion[];
}

/** A result message arrived: the agent finished its turn and it is yours. */
export interface DoneEvent {
  type: "done";
  sessionId: string;
  seq: number;
  subtype: DoneSubtype;
  isError: boolean;
  durationMs: number;
  numTurns: number;
  result: string | null;
}

/** Something the client asked for did not happen. Connection-scoped errors use the reserved '@registry' sessionId. */
export interface ErrorEvent {
  type: "error";
  sessionId: string;
  seq: number;
  code: ErrorCode;
  message: string;
  requestId: string | null;
}

/** canUseTool fired for a tool that is not AskUserQuestion. The agent is blocked until a decision or interrupt comes back. */
export interface PermissionEvent {
  type: "permission";
  sessionId: string;
  seq: number;
  requestId: string;
  tool: string;
  /** The tool input verbatim. */
  input: Record<string, unknown>;
  /** The actual command or path, never a summary. Approving what you cannot see is the failure mode this product designs against. */
  display: string;
  suggestions: PermissionSuggestion[];
}

/** A pending request stopped being pending - possibly answered from the CLI, the phone, or another watch. The watch cancels that notification. */
export interface ResolvedEvent {
  type: "resolved";
  sessionId: string;
  seq: number;
  requestId: string;
  resolution: Resolution;
  /** deviceId that answered, when a device did. */
  by: string | null;
}

/** Snapshot of every chat. Registry-scoped, so sessionId is the reserved id '@registry' and seq counts on the registry's own stream. */
export interface SessionsEvent {
  type: "sessions";
  sessionId: string;
  seq: number;
  sessions: SessionSummary[];
  maxSessions: number;
}

/** Assistant text, summarised rather than streamed. A watch does not need token-by-token deltas and not sending them is a meaningful battery saving. */
export interface TextEvent {
  type: "text";
  sessionId: string;
  seq: number;
  text: string;
}

/** The alerting event: this session's turn state changed. state == awaiting or idle is what buzzes the wrist; NotificationTransport consumes exactly this. */
export interface TurnEvent {
  type: "turn";
  sessionId: string;
  seq: number;
  state: SessionState;
  reason: TurnReason;
  /** The request that is blocking, when reason is ask or permission. Carried into the notification's RemoteInput so a dictated reply from the shade resolves this exact request. */
  requestId: string | null;
  /** Denormalised so a notification can be built from the turn event alone. */
  sessionName: string;
  /** One line, already shortened for a 1.5" screen. */
  summary: string;
}

/** Anything the watch may send. */
export type ClientMessage =
  | AnswerMessage
  | HelloMessage
  | InterruptMessage
  | NewSessionMessage
  | PermissionDecisionMessage
  | PromptMessage
  | RenameSessionMessage
  | SetModeMessage
  | SubscribeMessage;
export type ClientMessageType = ClientMessage["type"];

/** Anything the bridge may send. Every one carries sessionId and a per-session seq. */
export type ServerEvent =
  | AskEvent
  | DoneEvent
  | ErrorEvent
  | PermissionEvent
  | ResolvedEvent
  | SessionsEvent
  | TextEvent
  | TurnEvent;
export type ServerEventType = ServerEvent["type"];

export type ClientMessageOf<T extends ClientMessageType> = Extract<ClientMessage, { type: T }>;
export type ServerEventOf<T extends ServerEventType> = Extract<ServerEvent, { type: T }>;

export const CLIENT_MESSAGE_SCHEMAS: Readonly<Record<ClientMessageType, JsonSchema>> = {
  "answer": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "client/answer.schema.json",
    "title": "AnswerMessage",
    "description": "Answer an AskUserQuestion. Set answers to pick options (values are labels, or dictated free text). Set response instead to dismiss the questions and just talk to Claude. Exactly one of the two is non-null.",
    "x-message": {
      "direction": "client",
      "type": "answer"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "requestId",
      "answers",
      "response"
    ],
    "properties": {
      "type": {
        "const": "answer"
      },
      "sessionId": {
        "type": "string"
      },
      "requestId": {
        "type": "string"
      },
      "answers": {
        "description": "question text -> selected label. multiSelect answers are joined with ', '.",
        "type": [
          "object",
          "null"
        ],
        "additionalProperties": {
          "type": "string"
        }
      },
      "response": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "hello": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "client/hello.schema.json",
    "title": "HelloMessage",
    "description": "First frame after the WebSocket upgrade. The bearer token travelled on the upgrade request, not here.",
    "x-message": {
      "direction": "client",
      "type": "hello"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "protocolVersion",
      "deviceId",
      "deviceName",
      "clientVersion"
    ],
    "properties": {
      "type": {
        "const": "hello"
      },
      "protocolVersion": {
        "type": "integer"
      },
      "deviceId": {
        "type": "string"
      },
      "deviceName": {
        "type": "string"
      },
      "clientVersion": {
        "type": "string"
      }
    }
  },
  "interrupt": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "client/interrupt.schema.json",
    "title": "InterruptMessage",
    "description": "Stop a runaway agent from the wrist.",
    "x-message": {
      "direction": "client",
      "type": "interrupt"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId"
    ],
    "properties": {
      "type": {
        "const": "interrupt"
      },
      "sessionId": {
        "type": "string"
      }
    }
  },
  "newSession": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "client/new-session.schema.json",
    "title": "NewSessionMessage",
    "description": "Start a chat in a directory that already exists. The bridge never clones or provisions anything.",
    "x-message": {
      "direction": "client",
      "type": "newSession"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "cwd",
      "name"
    ],
    "properties": {
      "type": {
        "const": "newSession"
      },
      "cwd": {
        "type": "string"
      },
      "name": {
        "type": [
          "string",
          "null"
        ],
        "description": "Defaults to the cwd basename."
      }
    }
  },
  "permission": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "client/permission.schema.json",
    "title": "PermissionDecisionMessage",
    "description": "Answer a permission card. allowAlways additionally persists the localSettings suggestions the bridge sent with the request.",
    "x-message": {
      "direction": "client",
      "type": "permission"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "requestId",
      "decision",
      "message"
    ],
    "properties": {
      "type": {
        "const": "permission"
      },
      "sessionId": {
        "type": "string"
      },
      "requestId": {
        "type": "string"
      },
      "decision": {
        "$ref": "common.schema.json#/$defs/PermissionDecision"
      },
      "message": {
        "type": [
          "string",
          "null"
        ],
        "description": "Deny reason. Claude sees this, so it adapts instead of retrying blindly."
      }
    }
  },
  "prompt": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "client/prompt.schema.json",
    "title": "PromptMessage",
    "description": "Push a follow-up user message into a live session.",
    "x-message": {
      "direction": "client",
      "type": "prompt"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "text"
    ],
    "properties": {
      "type": {
        "const": "prompt"
      },
      "sessionId": {
        "type": "string"
      },
      "text": {
        "type": "string"
      }
    }
  },
  "renameSession": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "client/rename-session.schema.json",
    "title": "RenameSessionMessage",
    "description": "Relabel a chat. Every notification card leads with this name, which is what makes two waiting sessions answerable at a glance.",
    "x-message": {
      "direction": "client",
      "type": "renameSession"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "name"
    ],
    "properties": {
      "type": {
        "const": "renameSession"
      },
      "sessionId": {
        "type": "string"
      },
      "name": {
        "type": "string"
      }
    }
  },
  "setMode": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "client/set-mode.schema.json",
    "title": "SetModeMessage",
    "description": "Change a live session's permission mode. Raising it means fewer wrist buzzes and less oversight.",
    "x-message": {
      "direction": "client",
      "type": "setMode"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "mode"
    ],
    "properties": {
      "type": {
        "const": "setMode"
      },
      "sessionId": {
        "type": "string"
      },
      "mode": {
        "$ref": "common.schema.json#/$defs/PermissionMode"
      }
    }
  },
  "subscribe": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "client/subscribe.schema.json",
    "title": "SubscribeMessage",
    "description": "Ask for a full resync. The bridge answers with a sessions snapshot plus a replay of every outstanding request across all sessions.",
    "x-message": {
      "direction": "client",
      "type": "subscribe"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sinceSeq"
    ],
    "properties": {
      "type": {
        "const": "subscribe"
      },
      "sinceSeq": {
        "description": "sessionId -> highest seq the client already has. null means the client has nothing.",
        "type": [
          "object",
          "null"
        ],
        "additionalProperties": {
          "type": "integer"
        }
      }
    }
  },
};

export const SERVER_EVENT_SCHEMAS: Readonly<Record<ServerEventType, JsonSchema>> = {
  "ask": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "server/ask.schema.json",
    "title": "AskEvent",
    "description": "canUseTool fired for AskUserQuestion. The agent is blocked until an answer or interrupt comes back.",
    "x-message": {
      "direction": "server",
      "type": "ask"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "seq",
      "requestId",
      "questions"
    ],
    "properties": {
      "type": {
        "const": "ask"
      },
      "sessionId": {
        "type": "string"
      },
      "seq": {
        "type": "integer"
      },
      "requestId": {
        "type": "string"
      },
      "questions": {
        "description": "1-4 questions, 2-4 options each.",
        "type": "array",
        "items": {
          "$ref": "common.schema.json#/$defs/AskQuestion"
        }
      }
    }
  },
  "done": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "server/done.schema.json",
    "title": "DoneEvent",
    "description": "A result message arrived: the agent finished its turn and it is yours.",
    "x-message": {
      "direction": "server",
      "type": "done"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "seq",
      "subtype",
      "isError",
      "durationMs",
      "numTurns",
      "result"
    ],
    "properties": {
      "type": {
        "const": "done"
      },
      "sessionId": {
        "type": "string"
      },
      "seq": {
        "type": "integer"
      },
      "subtype": {
        "$ref": "common.schema.json#/$defs/DoneSubtype"
      },
      "isError": {
        "type": "boolean"
      },
      "durationMs": {
        "type": "integer"
      },
      "numTurns": {
        "type": "integer"
      },
      "result": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "error": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "server/error.schema.json",
    "title": "ErrorEvent",
    "description": "Something the client asked for did not happen. Connection-scoped errors use the reserved '@registry' sessionId.",
    "x-message": {
      "direction": "server",
      "type": "error"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "seq",
      "code",
      "message",
      "requestId"
    ],
    "properties": {
      "type": {
        "const": "error"
      },
      "sessionId": {
        "type": "string"
      },
      "seq": {
        "type": "integer"
      },
      "code": {
        "$ref": "common.schema.json#/$defs/ErrorCode"
      },
      "message": {
        "type": "string"
      },
      "requestId": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "permission": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "server/permission.schema.json",
    "title": "PermissionEvent",
    "description": "canUseTool fired for a tool that is not AskUserQuestion. The agent is blocked until a decision or interrupt comes back.",
    "x-message": {
      "direction": "server",
      "type": "permission"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "seq",
      "requestId",
      "tool",
      "input",
      "display",
      "suggestions"
    ],
    "properties": {
      "type": {
        "const": "permission"
      },
      "sessionId": {
        "type": "string"
      },
      "seq": {
        "type": "integer"
      },
      "requestId": {
        "type": "string"
      },
      "tool": {
        "type": "string"
      },
      "input": {
        "type": "object",
        "description": "The tool input verbatim."
      },
      "display": {
        "type": "string",
        "description": "The actual command or path, never a summary. Approving what you cannot see is the failure mode this product designs against."
      },
      "suggestions": {
        "type": "array",
        "items": {
          "$ref": "common.schema.json#/$defs/PermissionSuggestion"
        }
      }
    }
  },
  "resolved": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "server/resolved.schema.json",
    "title": "ResolvedEvent",
    "description": "A pending request stopped being pending - possibly answered from the CLI, the phone, or another watch. The watch cancels that notification.",
    "x-message": {
      "direction": "server",
      "type": "resolved"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "seq",
      "requestId",
      "resolution",
      "by"
    ],
    "properties": {
      "type": {
        "const": "resolved"
      },
      "sessionId": {
        "type": "string"
      },
      "seq": {
        "type": "integer"
      },
      "requestId": {
        "type": "string"
      },
      "resolution": {
        "$ref": "common.schema.json#/$defs/Resolution"
      },
      "by": {
        "type": [
          "string",
          "null"
        ],
        "description": "deviceId that answered, when a device did."
      }
    }
  },
  "sessions": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "server/sessions.schema.json",
    "title": "SessionsEvent",
    "description": "Snapshot of every chat. Registry-scoped, so sessionId is the reserved id '@registry' and seq counts on the registry's own stream.",
    "x-message": {
      "direction": "server",
      "type": "sessions"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "seq",
      "sessions",
      "maxSessions"
    ],
    "properties": {
      "type": {
        "const": "sessions"
      },
      "sessionId": {
        "type": "string"
      },
      "seq": {
        "type": "integer"
      },
      "sessions": {
        "type": "array",
        "items": {
          "$ref": "common.schema.json#/$defs/SessionSummary"
        }
      },
      "maxSessions": {
        "type": "integer"
      }
    }
  },
  "text": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "server/text.schema.json",
    "title": "TextEvent",
    "description": "Assistant text, summarised rather than streamed. A watch does not need token-by-token deltas and not sending them is a meaningful battery saving.",
    "x-message": {
      "direction": "server",
      "type": "text"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "seq",
      "text"
    ],
    "properties": {
      "type": {
        "const": "text"
      },
      "sessionId": {
        "type": "string"
      },
      "seq": {
        "type": "integer"
      },
      "text": {
        "type": "string"
      }
    }
  },
  "turn": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "server/turn.schema.json",
    "title": "TurnEvent",
    "description": "The alerting event: this session's turn state changed. state == awaiting or idle is what buzzes the wrist; NotificationTransport consumes exactly this.",
    "x-message": {
      "direction": "server",
      "type": "turn"
    },
    "type": "object",
    "additionalProperties": false,
    "required": [
      "type",
      "sessionId",
      "seq",
      "state",
      "reason",
      "requestId",
      "sessionName",
      "summary"
    ],
    "properties": {
      "type": {
        "const": "turn"
      },
      "sessionId": {
        "type": "string"
      },
      "seq": {
        "type": "integer"
      },
      "state": {
        "$ref": "common.schema.json#/$defs/SessionState"
      },
      "reason": {
        "$ref": "common.schema.json#/$defs/TurnReason"
      },
      "requestId": {
        "type": [
          "string",
          "null"
        ],
        "description": "The request that is blocking, when reason is ask or permission. Carried into the notification's RemoteInput so a dictated reply from the shade resolves this exact request."
      },
      "sessionName": {
        "type": "string",
        "description": "Denormalised so a notification can be built from the turn event alone."
      },
      "summary": {
        "type": "string",
        "description": "One line, already shortened for a 1.5\" screen."
      }
    }
  },
};

export const CLIENT_MESSAGE_TYPES: readonly ClientMessageType[] = ["answer", "hello", "interrupt", "newSession", "permission", "prompt", "renameSession", "setMode", "subscribe"];
export const SERVER_EVENT_TYPES: readonly ServerEventType[] = ["ask", "done", "error", "permission", "resolved", "sessions", "text", "turn"];
