/** Emits wear/protocol/src/main/kotlin/dev/claudewear/protocol/Protocol.kt from the schema IR. */
import { PROTOCOL_VERSION, REGISTRY_SESSION_ID } from "./schema.mjs";

export const KOTLIN_PACKAGE = "dev.claudewear.protocol";

const HEADER = `// Code generated by protocol/codegen -- DO NOT EDIT.
// Source of truth: protocol/schema/**. Regenerate with \`make protocol\` at the repo root.
// CI fails if this file is stale.

package ${KOTLIN_PACKAGE}

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject
`;

/**
 * JSON integers all map to Long. Uniformity beats a per-field Int/Long guess: seq and
 * the epoch-millis fields need Long anyway, and a mixed mapping is a silent overflow
 * waiting for the one field that got it wrong.
 */
function kotlinType(t) {
  const base = (() => {
    switch (t.kind) {
      case "string":
        return "String";
      case "integer":
        return "Long";
      case "number":
        return "Double";
      case "boolean":
        return "Boolean";
      case "json":
        return "JsonObject";
      case "ref":
        return t.name;
      case "array":
        return `List<${kotlinType(t.items)}>`;
      case "map":
        return `Map<String, ${kotlinType(t.values)}>`;
      case "const":
      case "inlineEnum":
        throw new Error(`${t.kind} is only expected on the discriminator, which Kotlin omits`);
      default:
        throw new Error(`unhandled type ${t.kind}`);
    }
  })();
  return t.nullable ? `${base}?` : base;
}

function enumConstant(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .toUpperCase();
}

function doc(text, indent = "") {
  if (!text) return "";
  return `${indent}/** ${text} */\n`;
}

function emitDataClass(struct, { superType = null, overrides = new Set() } = {}) {
  const out = [];
  out.push(doc(struct.doc));
  out.push("@Serializable\n");
  if (struct.wireType) out.push(`@SerialName(${JSON.stringify(struct.wireType)})\n`);
  out.push(`public data class ${struct.name}(\n`);
  // The `type` property is the polymorphic discriminator; kotlinx writes it from
  // @SerialName, so declaring it as a field would emit it twice.
  const fields = struct.fields.filter((f) => f.type.kind !== "const");
  for (const field of fields) {
    out.push(doc(field.doc, "    "));
    const prefix = overrides.has(field.name) ? "override val" : "public val";
    out.push(`    ${prefix} ${field.name}: ${kotlinType(field.type)},\n`);
  }
  out.push(`)${superType ? ` : ${superType}` : ""}\n`);
  return out.join("");
}

export function emitKotlin({ enums, structs, messages }) {
  const out = [HEADER];

  out.push(`
public const val PROTOCOL_VERSION: Long = ${PROTOCOL_VERSION}

/** Events that belong to the registry rather than to one chat carry this sessionId. */
public const val REGISTRY_SESSION_ID: String = ${JSON.stringify(REGISTRY_SESSION_ID)}
`);

  for (const e of enums) {
    out.push("\n");
    out.push(doc(e.doc));
    out.push("@Serializable\n");
    out.push(`public enum class ${e.name} {\n`);
    for (const v of e.values) {
      out.push(`    @SerialName(${JSON.stringify(v)}) ${enumConstant(v)},\n`);
    }
    out.push("}\n");
  }

  for (const s of structs) {
    out.push("\n");
    out.push(emitDataClass(s));
  }

  out.push(`
/** Anything the watch may send. */
@Serializable
public sealed interface ClientMessage

/** Anything the bridge may send. */
@Serializable
public sealed interface ServerEvent {
    public val sessionId: String

    /** Per-session monotonic sequence number, so the watch can spot a gap and resync. */
    public val seq: Long
}
`);

  for (const m of messages) {
    out.push("\n");
    const isServer = m.direction === "server";
    out.push(
      emitDataClass(m, {
        superType: isServer ? "ServerEvent" : "ClientMessage",
        overrides: isServer ? new Set(["sessionId", "seq"]) : new Set(),
      }),
    );
  }

  return out.join("");
}
