/** Emits bridge/src/protocol.ts from the schema IR. */
import { PROTOCOL_VERSION, REGISTRY_SESSION_ID } from "./schema.mjs";

const HEADER = `// Code generated by protocol/codegen -- DO NOT EDIT.
// Source of truth: protocol/schema/**. Regenerate with \`npm run codegen\` in bridge/,
// or \`make protocol\` at the repo root. CI fails if this file is stale.
`;

function screamingPlural(name) {
  const snake = name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
  return `${snake}S`;
}

function doc(text, indent = "") {
  if (!text) return "";
  return `${indent}/** ${text} */\n`;
}

function tsType(t) {
  const base = (() => {
    switch (t.kind) {
      case "string":
        return "string";
      case "integer":
      case "number":
        return "number";
      case "boolean":
        return "boolean";
      case "json":
        return "Record<string, unknown>";
      case "const":
        return JSON.stringify(t.value);
      case "ref":
        return t.name;
      case "inlineEnum":
        return t.values.map((v) => JSON.stringify(v)).join(" | ");
      case "array":
        return `${tsType(t.items)}[]`;
      case "map":
        return `Record<string, ${tsType(t.values)}>`;
      default:
        throw new Error(`unhandled type ${t.kind}`);
    }
  })();
  return t.nullable ? `${base} | null` : base;
}

function emitInterface(struct) {
  const lines = [];
  lines.push(doc(struct.doc));
  lines.push(`export interface ${struct.name} {\n`);
  for (const field of struct.fields) {
    lines.push(doc(field.doc, "  "));
    lines.push(`  ${field.name}: ${tsType(field.type)};\n`);
  }
  lines.push("}\n");
  return lines.join("");
}

export function emitTypeScript({ enums, structs, messages }) {
  const out = [HEADER];

  out.push(`
export const PROTOCOL_VERSION = ${PROTOCOL_VERSION};

/** Events that belong to the registry rather than to one chat carry this sessionId. */
export const REGISTRY_SESSION_ID = ${JSON.stringify(REGISTRY_SESSION_ID)};

export type JsonSchema = Readonly<Record<string, unknown>>;
`);

  for (const e of enums) {
    out.push("\n");
    out.push(doc(e.doc));
    out.push(`export type ${e.name} = ${e.values.map((v) => JSON.stringify(v)).join(" | ")};\n`);
    out.push(
      `export const ${screamingPlural(e.name)}: readonly ${e.name}[] = [${e.values
        .map((v) => JSON.stringify(v))
        .join(", ")}];\n`,
    );
  }

  for (const s of structs) {
    out.push("\n");
    out.push(emitInterface(s));
  }

  for (const m of messages) {
    out.push("\n");
    out.push(emitInterface(m));
  }

  const client = messages.filter((m) => m.direction === "client");
  const server = messages.filter((m) => m.direction === "server");

  out.push(`
/** Anything the watch may send. */
export type ClientMessage =\n${client.map((m) => `  | ${m.name}`).join("\n")};
export type ClientMessageType = ClientMessage["type"];

/** Anything the bridge may send. Every one carries sessionId and a per-session seq. */
export type ServerEvent =\n${server.map((m) => `  | ${m.name}`).join("\n")};
export type ServerEventType = ServerEvent["type"];

export type ClientMessageOf<T extends ClientMessageType> = Extract<ClientMessage, { type: T }>;
export type ServerEventOf<T extends ServerEventType> = Extract<ServerEvent, { type: T }>;
`);

  const schemaMap = (list, tsName, keyType) =>
    `\nexport const ${tsName}: Readonly<Record<${keyType}, JsonSchema>> = {\n${list
      .map((m) => `  ${JSON.stringify(m.wireType)}: ${JSON.stringify(m.schema, null, 2).replace(/\n/g, "\n  ")},`)
      .join("\n")}\n};\n`;

  out.push(schemaMap(client, "CLIENT_MESSAGE_SCHEMAS", "ClientMessageType"));
  out.push(schemaMap(server, "SERVER_EVENT_SCHEMAS", "ServerEventType"));

  out.push(
    `\nexport const CLIENT_MESSAGE_TYPES: readonly ClientMessageType[] = [${client
      .map((m) => JSON.stringify(m.wireType))
      .join(", ")}];\n`,
  );
  out.push(
    `export const SERVER_EVENT_TYPES: readonly ServerEventType[] = [${server
      .map((m) => JSON.stringify(m.wireType))
      .join(", ")}];\n`,
  );

  return out.join("");
}
